#!/usr/bin/env bash

MPATH=com.udacity.catpoint.image/target/classes:com.udacity.catpoint.security/target/classes
MPATH=$MPATH:~/.m2/repository/com/miglayout/miglayout-swing/11.0
MPATH=$MPATH:~/.m2/repository/com/google/code/gson/gson/2.9.0
MPATH=$MPATH:~/.m2/repository/com/google/guava/guava/16.0.1/

java -p $MPATH  --module com.udacity.catpoint.security/com.udacity.catpoint.application.CatpointApp
